### ISSUE TITLE
Typo in Lab Report template

### ISSUE THREAD

**Issue by jshodd** [whosiflynn/OSCPExamTemplate#3]
Hi there, 

These templates are great and really give students a head start in figuring out how to structure their reports, so thanks for your contribution to the community! I just wanted to let you know there is a typo in section 1.2. It looks like you did a find replace for s/exam/Lab/g on these documents and it looks like that converted `example` to `Labple` in the objective statement. This typo also exists in the title page in the form of `Labple@Labple.Labple`, but students are more likely to change that. I just wanted to make sure students don't blindly copy and paste that section in and end up with a typo. 

Thanks again for this repo!

**Comment by whoisflynn** [comment]
Great find! When I get home next week I’ll fix it up

**Comment by whoisflynn** [comment]
Fixed
